language: ruby
rvm:
  - 2.7.2

cache: bundler 

before_script:
 - chmod +x ./.script/cibuild

before_install: gem update bundler
install:
  - bundle install

script: ./.script/cibuild

branches:
  only:
  - master

notifications:
  email: false

sudo: false
